manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .
    default_ttl: 3600
    enforce_order: false
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  mattglei.ch.:
    sources:
      - config
    targets:
      - cloudflare
